name: Run tests

on:
 push:
  branches: ['master']
 pull_request:
   branches: ['master']

   
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Install dependencies  
        run: npm install
      
      - name: Run tests
        run: npm test

        
